---
title: "MethComp Data Sets"
author: "KevinOBrien"
date: "18 September 2018"
output: html_document
---

```{r setup, include=FALSE}
library(MethComp)
library(nlme)
library(lme4)
library(magrittr)
library(tidyr)
library(broom)
library(dplyr)
```

```{r}
data(ox)
head(ox)
```

```{r}
# Analysis under Bland and Altman
# Analysis under Roy's Method
#       - Implementation of the four models
#       - Expression of the Matrices
#       - Implementation of the three hypothesis tests        
# Analysis under BXC
#       - Computation of Limits of Agreement
#################################################################
#
# Load useful packages for analysis
library(MethComp)
library(nlme)
```
```{r,echo=FALSE}
data(ox)
summary(ox)
ox$item <- factor(ox$item)
ox$repl <- factor(ox$repl)
dat=ox
```

```{r}
ox.roy1 = lme(y ~ meth-1, data = dat,
              random = list(item=pdSymm(~ meth-1)), 
              weights=varIdent(form=~1|meth),
              correlation = corSymm(form=~1 | item/repl), 
              method="ML")
ox.roy2 = lme(y ~ meth-1, data = dat,
              random = list(item=pdCompSymm(~ meth-1)), 
              correlation = corSymm(form=~1 | item/repl), 
              method="ML")
ox.roy3 = lme(y ~ meth-1, data = dat,
              random = list(item=pdSymm(~ meth-1)),
              weights=varIdent(form=~1|meth), 
              correlation = corCompSymm(form=~1 | item/repl), method="ML")
ox.roy4 = lme(y ~ meth-1, data = dat,
              random = list(item=pdCompSymm(~ meth-1)), 
              correlation = corCompSymm(form=~1 | item/repl), 
              method="ML")
#getSigma(ox.roy1)
#getOmega(ox.roy1)
#roy.SDV(ox.roy1)
```
## Analysis using BXC
```{r}
ox.bxc1 = lme( y ~ meth + item, random = list( item = pdIdent( ~ meth-1 ) ), 
               weights = varIdent( form = ~1 | meth ), data=dat)
ox.bxc2 = lme( y ~ meth + item, random=list( item = pdIdent( ~ meth-1 ), repl = ~1 ), 
               weights = varIdent( form = ~1 | meth ), data=dat )
ox.bxc3 = lme( y ~ meth + item, random=list( item = pdIdent( ~ meth-1 ), repl = ~1 ),
               weights = varIdent( form = ~1 | meth ),
               correlation = corCompSymm(form=~1 | item/repl ),data=dat)

```