---
title: "MethComp Data Sets"
author: "KevinOBrien"
date: "18 September 2018"
output: html_document
---

```{r setup, include=FALSE}
library(MethComp)
library(nlme)
library(lme4)
library(magrittr)
library(tidyr)
library(broom)
library(dplyr)
```

```{r}
data(milk)

milk <- milk %>% gather("Meth","y",Sub:Vic)
milk <- milk %>% set_colnames(c("item","obs","repl","meth","y"))
milk %>% filter(item == 1)
```

```{r}
# Analysis under Bland and Altman
# Analysis under Roy's Method
#       - Implementation of the four models
#       - Expression of the Matrices
#       - Implementation of the three hypothesis tests        
# Analysis under BXC
#       - Computation of Limits of Agreement
#################################################################
#
# Load useful packages for analysis

```


```{r}

dat=milk

milk.roy1 = lme(y ~ meth-1, data = dat,
              random = list(item=pdSymm(~ meth-1)), 
              weights=varIdent(form=~1|meth),
              correlation = corSymm(form=~1 | item/repl), 
              method="ML")
milk.roy2 = lme(y ~ meth-1, data = dat,
              random = list(item=pdCompSymm(~ meth-1)), 
              correlation = corSymm(form=~1 | item/repl), 
              method="ML")
milk.roy3 = lme(y ~ meth-1, data = dat,
              random = list(item=pdSymm(~ meth-1)),
              weights=varIdent(form=~1|meth), 
              correlation = corCompSymm(form=~1 | item/repl), method="ML")
milk.roy4 = lme(y ~ meth-1, data = dat,
              random = list(item=pdCompSymm(~ meth-1)), 
              correlation = corCompSymm(form=~1 | item/repl), 
              method="ML")
#getSigma(milk.roy1)
#getOmega(milk.roy1)
#roy.SDV(milk.roy1)
```
## Analysis using BXC
```{r}
milk.bxc1 = lme( y ~ meth + item, random = list( item = pdIdent( ~ meth-1 ) ), 
               weights = varIdent( form = ~1 | meth ), data=dat)
milk.bxc2 = lme( y ~ meth + item, random=list( item = pdIdent( ~ meth-1 ), repl = ~1 ), 
               weights = varIdent( form = ~1 | meth ), data=dat )
milk.bxc3 = lme( y ~ meth + item, random=list( item = pdIdent( ~ meth-1 ), repl = ~1 ),
               weights = varIdent( form = ~1 | meth ),
               correlation = corCompSymm(form=~1 | item/repl ),data=dat)

```

```{r}
 tidy(milk.roy) # conditional Residuals 
```

```{r}
getLOA(milk.roy) 
```
